yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug>', views.group_posts, name='group'),
    path('', views.index, name='glang'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Заголовок', max_length=200)
    slug = models.SlugField('Путь', unique=True)
    description = models.TextField('Oписание', max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группы'


class Post(models.Model):
    text = models.TextField('Текст поста',)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
    )

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Посты'
        ordering = ('-pub_date',)

yatube/posts/views.py
# posts/views.py
from django.shortcuts import get_object_or_404, render

from .models import Group, Post


def index(request):
    posts = Post.objects.order_by()[:10]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
{% load static %}
<!-- templates/base.html -->
<!DOCTYPE html> 
<html lang="ru">          
  <head>
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
{% load static %}
<footer class="border-top text-center py-3">
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
    <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
  </footer>
</body>

yatube/templates/includes/header.html
{% load static %}


<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Yatube</title>
  </head>
  <body>
    <header>
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:glang' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
          </a>
        </div>
      </nav>      
    </header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Записи сообщества {{ group.title }}{% endblock title %}

  {% block content %}
    <!-- класс py-5 создает отступы сверху и снизу блока -->
    <div class="container py-5">
      <h1>{{ group.title }}</h1>
      <p>
        {{ group.description }}
      </p>
      {% for post in posts%}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name}}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        <p>
          {{ post.text }}
        </p>
      </ul> 
      <p>
        {{ post.title }}
      </p>
      {% if not forloop.last %} <hr> {% endif %}
      {% endfor %}
  {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
<!--{% block title %} Главная страница{% endblock title %}-->
{% block content %}    
<main> 
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">     
    <h1>{{ title }}</h1>
    <article>
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        {% if post.group %}   
          <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
        {% endif %} 
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
    </article>
    <hr>

    <!-- под последним постом нет линии -->
  </div>  
</main>
<!-- Использованы классы бустрапа: -->
<!-- border-top: создаёт тонкую линию сверху блока -->
<!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
<!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
{% endblock content %}